"""add unique constraint on category user_id and name

Revision ID: 993cda0e8337
Revises: 531321bca683
Create Date: 2026-09-15 09:19:03.203549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993cda0e8337'
down_revision: Union[str, Sequence[str], None] = '531321bca683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_user_name', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_user_name', 'categories', type_='unique')
    # ### end Alembic commands ###
